-- Retired EPS, reported-fundamental and price definitions are no longer part
-- of the Metrics Overview schema. Remove their observations first because the
-- foreign key deliberately has no cascading delete.
DELETE FROM `metric_observations`
WHERE `metric_definition_id` IN (
  'security:pe_ttm:v1',
  'security:pe_normalized_ttm:v1',
  'security:pe_forward_fy:v1',
  'security:pe_forward_consensus_6m_annualized:v1',
  'security:pe_last_quarter_annualized:v1',
  'security:pe_last_quarter_adjusted_annualized:v1',
  'security:pe_next_quarter_annualized:v1',
  'security:eps_growth_forward_fy:v1',
  'security:eps_growth_forward_consensus_6m:v1',
  'security:eps_growth_ttm_yoy:v1',
  'security:close:v1',
  'security:eps_diluted_ttm:v1',
  'security:eps_diluted_fy:v1',
  'security:eps_diluted_fq:v1',
  'security:eps_headline_fy:v1',
  'security:eps_headline_fq:v1',
  'security:eps_forecast_next_fy:v1',
  'security:eps_forecast_next_fq:v1',
  'security:eps_forecast_next_fh:v1',
  'security:operating_income_fq:v1',
  'security:operating_income_fy:v1',
  'security:operating_income_ttm:v1',
  'security:net_income_fq:v1',
  'security:net_income_fy:v1',
  'security:net_income_ttm:v1',
  'security:diluted_shares_fq:v1',
  'security:unusual_income_expense_fq:v1',
  'security:eps_adjusted_fq:v1',
  'security:eps_adjusted_ttm:v1',
  'security:net_to_operating_income_fq:v1'
);
--> statement-breakpoint
DELETE FROM `metric_definitions`
WHERE `id` IN (
  'security:pe_ttm:v1',
  'security:pe_normalized_ttm:v1',
  'security:pe_forward_fy:v1',
  'security:pe_forward_consensus_6m_annualized:v1',
  'security:pe_last_quarter_annualized:v1',
  'security:pe_last_quarter_adjusted_annualized:v1',
  'security:pe_next_quarter_annualized:v1',
  'security:eps_growth_forward_fy:v1',
  'security:eps_growth_forward_consensus_6m:v1',
  'security:eps_growth_ttm_yoy:v1',
  'security:close:v1',
  'security:eps_diluted_ttm:v1',
  'security:eps_diluted_fy:v1',
  'security:eps_diluted_fq:v1',
  'security:eps_headline_fy:v1',
  'security:eps_headline_fq:v1',
  'security:eps_forecast_next_fy:v1',
  'security:eps_forecast_next_fq:v1',
  'security:eps_forecast_next_fh:v1',
  'security:operating_income_fq:v1',
  'security:operating_income_fy:v1',
  'security:operating_income_ttm:v1',
  'security:net_income_fq:v1',
  'security:net_income_fy:v1',
  'security:net_income_ttm:v1',
  'security:diluted_shares_fq:v1',
  'security:unusual_income_expense_fq:v1',
  'security:eps_adjusted_fq:v1',
  'security:eps_adjusted_ttm:v1',
  'security:net_to_operating_income_fq:v1'
);
